      PROGRAM DATAS
      IMPLICIT NONE
      REAL*8 HH,JD
      INTEGER YY, MM, DD, OPTION
      CHARACTER*10 DSEMANA
      WRITE(6,*)'Tipo de Entrada'
      WRITE(6,*)'1.AMDH'
      WRITE(6,*)'2.JD'
      READ(5,*) OPTION
      IF(OPTION.EQ.1) THEN
      	WRITE(6,*)'ANO,MES,DIA,HORA'
      	READ(5,*)YY,MM,DD,HH
     	CALL CAL2JD (YY,MM,DD,HH,JD)
      ELSE IF(OPTION.EQ.2) THEN
      	WRITE(6,*)'JD'
      	READ(5,*)JD
     	CALL JD2CAL (JD,YY,MM,DD,HH,DSEMANA)
      ELSE
     	WRITE(6,*)'WRONG OPTION'
      END IF
      END 	 
      
      SUBROUTINE CAL2JD(ANO,MES,DIA,HORA,JD)
      IMPLICIT NONE
      REAL*8 HORA,JD
      INTEGER ANO,MES,DIA,M,Y
      IF (MES.LE.2) THEN
      	M=MES+12
      	Y=ANO-1
      ELSE
      	M=MES
      	Y=ANO
      END IF
      JD = INT(365.25*Y)+INT(30.6001*(M+1))+DIA+HORA/24+1720981.5
      WRITE(6,*)JD
      END
      
      SUBROUTINE JD2CAL(JD,ANO,MES,DIA,HORA,DSEMANA)
      IMPLICIT NONE
      REAL*8 HORA,JD
      INTEGER ANO,MES,A,B,C,D,E, DIA,N
      CHARACTER*10 DSEMANA
      A=INT(JD+0.5)
      B=A+1537
      C=INT((B-122.1)/365.25)
      D=INT(365.25*C)
      E=INT((B-D)/30.6001)
      DIA=B-D-INT(30.6001*E)
      MES=E-1-12*INT(E/14)
      ANO=C-4715-INT((7+MES)/10)
      HORA=(JD+0.5-A)*24
      N=MOD(INT(JD+0.5),7)
      IF(N.EQ.0) THEN
      	DSEMANA = 'MONDAY'
      ELSE IF(N.EQ.1) THEN
      	DSEMANA = 'TUESDAY'
      ELSE IF(N.EQ.2) THEN
      	DSEMANA = 'WEDNESDAY'
      ELSE IF(N.EQ.3) THEN
      	DSEMANA = 'THURSDAY'
      ELSE IF(N.EQ.4) THEN
      	DSEMANA = 'FRIDAY'
      ELSE IF(N.EQ.5) THEN
      	DSEMANA = 'SATURDAY'
      ELSE
      	DSEMANA = 'SUNDAY'
      END IF
      WRITE(6,*) ANO,MES,DIA,HORA,DSEMANA
      END
      
      
      
